FROM certbot/certbot

#RUN printf '%s\n' zamyatin.daniil@gmail.com Y Y daniilz.ru /app/docker/letsen | certbot certonly --webroot
#RUN cp -R /etc/letsencrypt/archive/daniilz.ru /app/
#/etc/letsencrypt/live/

ENTRYPOINT while true; do echo 1; sleep 1; done
